export const CONFIG = {
    DEFAULT_VIEW: "assistant",
    LIVE2D_CONFIG: {
        HEIGHT: 520,
        WIDTH: 900,
        TIMEOUT_MS: 3000,
        SHORTEST_TIME_GAP: 100,
        AUTO_EXPAND_LENGTH: 220,
        AUTO_EXPAND_LINES: 6,
        model: {
            jsonFile: "../assets/live2d/Hiyori/Hiyori.model3.json",
        },
    },
    ASSISTANT_CONFIG: {
        STREAM_DELAY_MS: 14,
        REQUEST_TIMEOUT_MS: 90000,
        NEAR_BOTTOM_OFFSET: 48,
        BUBBLE_LABEL_RESPONSE: "Response",
        BUBBLE_LABEL_TOUCH: "Touch",
        BUBBLE_EXPAND_ARIA_LABEL: "Expand chat panel",
        CHAT_MODE_EXPANDED: "Right Panel",
        CHAT_MODE_COMPACT: "Bubble",
        ROLE_USER: "user",
        ROLE_ASSISTANT: "assistant",
        ROLE_AGENT: "agent",
        STATUS_SENT: "sent",
        STATUS_PREPARING: "preparing",
        STATUS_STREAMING: "streaming",
        STATUS_DONE: "done",
        STATUS_ERROR: "error",
        STATUS_PHASE_PREFETCH: "Preparing context",
        STATUS_PHASE_THINKING: "Thinking",
        STATUS_PHASE_TOOL: "Using tool",
        STATUS_STEP_SUFFIX: "step",
        STATUS_TOOL_PREFIX: "Tool",
        STATUS_CANCELED: "canceled",
        STATUS_TIMEOUT: "timed out",
        STATUS_CANCELING: "canceling",
        TRACE_STEPS_SUFFIX: "steps",
        THINKING_TEXT: "Thinking...",
        REQUEST_FAILED_TEXT: "Request failed. Please retry.",
        REQUEST_CANCELED_TEXT: "Request canceled.",
        REQUEST_TIMEOUT_TEXT: "Request timed out. Please retry.",
        REQUEST_RETRY_LABEL: "Retry",
        REQUEST_CANCEL_LABEL: "Cancel",
        REQUEST_SEND_LABEL: "Send",
        RUN_PANEL_TOGGLE_EXPAND: "展开详情",
        RUN_PANEL_TOGGLE_COLLAPSE: "收起详情",
        TRACE_STEP_LABEL: "Step",
        TRACE_PHASE_LABEL: "Phase",
        TRACE_STATUS_LABEL: "Status",
        TRACE_DEFAULT_TOOL: "tool",
        TRACE_DEFAULT_STATUS: "unknown",
        RUN_PANEL_TITLE: "Execution Panel",
        RUN_PANEL_DESC: "Current agent state and completed tool steps.",
        RUN_PANEL_IDLE: "Idle",
        RUN_PANEL_EMPTY: "No execution steps yet.",
        RUN_PANEL_CURRENT: "Current",
        RUN_PANEL_SUMMARY_IDLE: "当前没有思考或工具调用过程。",
    },
    CARDS_CONFIG: {
        PAGE_SIZE: 8,
        PAGE_SIZE_WIDE: 10,
        PAGE_SIZE_ULTRA: 12,
        COPY: {
            cardsTotal: "卡片总数",
            categoryTotal: "分类数",
            title: "知识卡片箱",
            desc: "默认显示卡片列表。单击选中，双击打开；新建和编辑在独立工作区内完成。",
            searchLabel: "搜索",
            searchPlaceholder: "按标题、分类或正文内容搜索",
            create: "新建",
            edit: "编辑",
            remove: "删除",
            category: "分类",
            allCategories: "全部分类",
            backToList: "返回卡片列表",
            createMode: "新建卡片",
            editMode: "编辑卡片",
            createTitle: "整理一张新的知识卡片",
            editTitle: "调整这张知识卡片",
            editorDesc: "标题、分类与摘要集中在上方，正文支持 Markdown，右侧可实时检查排版效果。",
            save: "保存卡片",
            cancel: "取消",
            titleField: "标题",
            categoryField: "分类",
            editorField: "编辑区",
            previewField: "预览区",
            summaryField: "卡片摘要",
            summaryPlaceholder: "在这里查看或手动调整卡片摘要",
            summaryGenerate: "智能生成摘要",
            summaryGenerating: "正在生成摘要...",
            titlePlaceholder: "例如：三月项目切换策略",
            categoryPlaceholder: "例如：项目、灵感、设定",
            contentPlaceholder: "输入 Markdown 内容",
            localStatus: "内容会直接写入本地 JSON。",
            editingCreate: "编辑中，可随时保存卡片。",
            editingUpdate: "编辑中，可随时保存更新。",
            savingCreate: "正在保存卡片...",
            savingUpdate: "正在更新卡片...",
            savedCreate: "已保存：",
            savedUpdate: "已更新：",
            untitled: "未命名卡片",
            uncategorized: "未分类",
            previewEmpty: "尚未填写内容。",
            noTime: "未记录时间",
            pagePrev: "上一页",
            pageNext: "下一页",
            pageMeta: (page, totalPages, totalItems) => `第 ${page} / ${totalPages} 页，共 ${totalItems} 条`,
            categoriesInline: (count) => `${count} 类`,
            creatorPrefix: "创建者",
            createdPrefix: "创建时间",
            editHint: (title) => `正在编辑：${title}`,
            emptyTitle: "没有匹配的知识卡片",
            emptyDesc: "可以调整搜索或切换分类，也可以直接新建卡片。",
            modalLabel: "知识卡片详情",
            confirmCreateAbandon: "当前有未保存内容，确定放弃并新建卡片吗？",
            confirmEditAbandon: "当前有未保存内容，确定放弃并切换到其他卡片吗？",
            confirmBackAbandon: "当前有未保存内容，确定返回列表吗？",
            confirmDelete: (title) => `确定删除卡片“${title}”吗？`,
        },
    },
};
